# base image
FROM continuumio/miniconda3:4.6.14

# Dockerfile author / maintainer 
LABEL maintainer="AakashMallik <humble.discipulus@gmail.com>"

# copy files to container
COPY . /usr/src/app

# change working directory
WORKDIR /usr/src/app

# install python dependencies
RUN pip install kafka-python

# start python interface
CMD python interface.py